/*
New Wheels Business Performance Analysis
Author: Briana Salinas

This file contains SQL queries used to analyze:
- Customer distribution
- Customer satisfaction
- Manufacturer preferences
- Revenue trends
- Shipping performance
*/

-- Question 1a: Total number of customers who placed orders
SELECT
    COUNT(DISTINCT c.customer_id) AS total_customers
FROM customer_t AS c
JOIN order_t AS o 
    ON c.customer_id = o.customer_id;


-- Question 1b: Distribution of customers across states
SELECT
    state,
    COUNT(customer_id) AS total_customers
FROM customer_t
GROUP BY state
ORDER BY total_customers DESC;


-- Question 2: Top 5 vehicle makers preferred by customers
SELECT
    p.vehicle_maker,
    COUNT(DISTINCT o.customer_id) AS customer_count
FROM product_t AS p
JOIN order_t AS o 
    ON p.product_id = o.product_id
GROUP BY p.vehicle_maker
ORDER BY customer_count DESC
LIMIT 5;


-- Question 3: Most preferred vehicle maker in each state
-- Note: RANK() returns all tied top vehicle makers within each state.
SELECT
    state,
    vehicle_maker,
    customer_count
FROM (
    SELECT
        c.state,
        p.vehicle_maker,
        COUNT(DISTINCT o.customer_id) AS customer_count,
        RANK() OVER (
            PARTITION BY c.state
            ORDER BY COUNT(DISTINCT o.customer_id) DESC
        ) AS rnk
    FROM product_t AS p
    JOIN order_t AS o 
        ON p.product_id = o.product_id
    JOIN customer_t AS c 
        ON o.customer_id = c.customer_id
    GROUP BY c.state, p.vehicle_maker
) AS ranked
WHERE rnk = 1
ORDER BY state;


-- Question 4a: Overall average rating given by customers
SELECT
    AVG(rating_score) AS overall_avg_rating
FROM (
    SELECT
        CASE customer_feedback
            WHEN 'Very Bad' THEN 1
            WHEN 'Bad' THEN 2
            WHEN 'Okay' THEN 3
            WHEN 'Good' THEN 4
            WHEN 'Very Good' THEN 5
            ELSE NULL
        END AS rating_score
    FROM order_t
) AS ratings;


-- Question 4b: Average rating by quarter
SELECT
    quarter_number,
    ROUND(AVG(rating_score), 3) AS avg_rating
FROM (
    SELECT
        quarter_number,
        CASE customer_feedback
            WHEN 'Very Bad' THEN 1
            WHEN 'Bad' THEN 2
            WHEN 'Okay' THEN 3
            WHEN 'Good' THEN 4
            WHEN 'Very Good' THEN 5
            ELSE NULL
        END AS rating_score
    FROM order_t
) AS ratings
GROUP BY quarter_number
ORDER BY quarter_number;


-- Question 5: Percentage distribution of customer feedback by quarter
SELECT
    quarter_number,
    ROUND(COUNT(CASE WHEN customer_feedback = 'Very Bad' THEN 1 END) * 100.0 / COUNT(*), 2) AS very_bad_pct,
    ROUND(COUNT(CASE WHEN customer_feedback = 'Bad' THEN 1 END) * 100.0 / COUNT(*), 2) AS bad_pct,
    ROUND(COUNT(CASE WHEN customer_feedback = 'Okay' THEN 1 END) * 100.0 / COUNT(*), 2) AS okay_pct,
    ROUND(COUNT(CASE WHEN customer_feedback = 'Good' THEN 1 END) * 100.0 / COUNT(*), 2) AS good_pct,
    ROUND(COUNT(CASE WHEN customer_feedback = 'Very Good' THEN 1 END) * 100.0 / COUNT(*), 2) AS very_good_pct
FROM order_t
GROUP BY quarter_number
ORDER BY quarter_number;


-- Question 6: Trend of number of orders by quarter
SELECT
    quarter_number,
    COUNT(order_id) AS total_orders
FROM order_t
GROUP BY quarter_number
ORDER BY quarter_number;


-- Question 7a: Net revenue generated by the company
SELECT
    ROUND(SUM(quantity * (vehicle_price * (1 - discount / 100.0))), 3) AS net_revenue
FROM order_t;


-- Question 7b: Quarter-over-quarter percentage change in net revenue
SELECT
    quarter_number,
    net_revenue,
    ROUND(
        (net_revenue - LAG(net_revenue) OVER (ORDER BY quarter_number))
        * 100.0 / LAG(net_revenue) OVER (ORDER BY quarter_number),
        2
    ) AS percent_diff
FROM (
    SELECT
        quarter_number,
        ROUND(SUM(quantity * (vehicle_price * (1 - discount / 100.0))), 3) AS net_revenue
    FROM order_t
    GROUP BY quarter_number
) revenue_by_quarter
ORDER BY quarter_number;


-- Question 8: Trend of net revenue and orders by quarter
SELECT
    quarter_number,
    ROUND(SUM(vehicle_price * quantity * (1 - discount / 100.0)), 3) AS net_revenue,
    COUNT(order_id) AS number_orders
FROM order_t
GROUP BY quarter_number
ORDER BY quarter_number;


-- Question 9: Average discount offered for different credit card types
SELECT
    c.credit_card_type,
    ROUND(AVG(o.discount), 2) AS avg_discount
FROM order_t AS o
JOIN customer_t AS c
    ON o.customer_id = c.customer_id
GROUP BY c.credit_card_type
ORDER BY c.credit_card_type;

/*
Note:
The original course environment used the julianday() function for
date calculations. In MySQL, the equivalent calculation would be:

DATEDIFF(ship_date, order_date)

The original query has been preserved to match the course submission.
*/

-- Question 10: Average time taken to ship orders by quarter
SELECT
    quarter_number,
    ROUND(AVG(julianday(ship_date) - julianday(order_date)), 2) AS avg_days_to_ship
FROM order_t
GROUP BY quarter_number
ORDER BY quarter_number;
